### ISSUE TITLE
Undeclared dependnecy on Moose and Dist::Zilla::Role::PluginBundle::Easy

### ISSUE THREAD

**Issue by andk** [bessarabov/Dist-Zilla-PluginBundle-BESSARABV#1]
As per subject. Witness grep:

http://search.cpan.org/grep?release=Dist-Zilla-PluginBundle-BESSARABV-0.02;string=Dist::Zilla::Role::PluginBundle::Easy|Moose;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/29789255

HTH&&Regards,

**Comment by bessarabov** [comment]
Thank you for your report!

It is very funny, but I have released version 0.03 of this module in about an hour before your post =) I've fixed dependencies in that release.

Version 0.03 is on CPAN now. I've just installed in on an empty virtual machine and everything installed correctly.

cpantesters.org does not tested that release yet, but I hope everything will be fine.

I will close this issue after I will receive some mail from cpantesters.

**Comment by andk** [comment]
Ivan Bessarabov notifications@github.com writes:

> It is very funny, but I have released version 0.03 of this module in about an
> hour before your post =) I've fixed dependencies in that release.

:)

> Version 0.03 is on CPAN now. I've just installed in on an empty virtual machine
> and everything installed correctly.
> 
> cpantesters.org does not tested that release yet, but I hope everything will be
> fine.
> 
> I will close this issue after I will receive some mail from cpantesters.

My smoker was borked last night, it has cought up in the meantime, and
the results look good; it has sent 32 pass reports, no fail.

## 

andreas

**Comment by bessarabov** [comment]
I've checked the state of the tests on page http://www.cpantesters.org/distro/D/Dist-Zilla-PluginBundle-BESSARABV.html#Dist-Zilla-PluginBundle-BESSARABV-0.03

Everything is ok no, so, I'm closing this quest.

@andk, thank you for this issue!

PS here is the scrrenshot of the tests page: https://f.cloud.github.com/assets/47263/655567/7cc9b534-d516-11e2-890a-d87bda7bc528.png (be carefull it it huge, 4,5 megabytes)
